name: groceries_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  bottom_bar_matu: ^1.5.0 # Add the appropriate version here
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/Group.png
    - assets/image/8140 1.png
    - assets/image/Mask Group.png
    - assets/image/

  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Medium.ttf
